# Logistics {.unnumbered}

Organizing a coding cafe requires some logistics, as for every event. However, coding cafes may come with special requirements that you need to take into account. The key message of this chapter is:

> Know your audience!

## Frequency

Finding the right frequency for you as an organizer AND your community is crucial for the sustainability of your programming cafe. Your cafe will not be a success if you are eager to meet as often as possible, but your community consists of programmers with extremely busy schedules. Meeting too often may be exhausting for you as an organizer, and frustrating for your community as being pushed to constantly declining events may feel overwhelming. However, meeting only once in a blue moon is certainly not frequently enough to build strong bonds in your community. 

Finding the right balance is important. Try to find out what frequency may be seen as a standard for your audience and live within the rhythm of your institution. You can also reach out to partner institutions that already have experience and ask for advice. Nothing is written in stone: you can later change the frequency based on your experience.

As a suggestion: most of our coding cafes are organized on a monthly basis with a dynamic audience. That means that some people will join most of your events while others may only come irregularly for certain topics. However, some coding cafes do not follow a strict schedule but are organized ad-hoc once there are enough speakers, topics, or volunteers. 

## Best dates & times

Finding your rhythm is important, but not enough. Making exceptions to your frequency may be necessary. Some events may alter your planning such as for example:

- holidays (your attendance will probably be low if you plan an in-person coding event on Christmas Eve);
- vacation season (be mindful of potential school holiday breaks in your region if your community consists of programmers with families for example);
- exam or internship weeks at your university (if you are inviting students to your events make sure that they are around to join);
- major events at your institution that will be prioritized by your community (do not plan a coding cafe as an alternative to a major software related conference at your institution for example).

Additionally, planning around events that bring a lot of people together anyway may be beneficial. If you know that your audience will come together for a shorter event, you may want to try to get them after the event for your programming cafe.

Finding the right week day and the best day time is equally important. A lot of institutions are offering telework options. Some of your colleagues may work part-time, or researchers may split their time between multiple institutions. That means that not everyone will be available to join an event on campus on certain days. If you know your audience well, you may avoid some pitfalls with setting the date. Mondays and Fridays may be preferred telework days for example, so plan accordingly on other days. 

Depending on your format, certain times during the day may be more suitable than others. If you offer food and drinks for example, you may benefit from setting your coding cafe during lunch hours or organize it in the late afternoons as an early dinner option.


## Food & drinks

No one likes to work on an empty stomach - same goes for programming. Offering food or drinks may help to increase the mood of the audience and may attract some additional people. There will probably be a lot of events and meetings to choose from on busy days, and offering snacks or drinks may help people to decide to spend their time at your coding cafe. Some advantages of offering food and drinks are:

- Increase of attraction;
- Increase of happiness;
- Works as an icebreaker since people come together at a potential buffet.

However, providing foods and drinks also comes with disadvantages such as

- Increase of cost;
- Increase of organizational effort.

If you order pizza for example for all participants, you need a higher budget and you have an additional effort of ordering and receiving pizza in time.

There is a vast amount of choices for selecting the right food and drinks for your audience. If you organize an event for a vegan audience, offering steaks for barbecue seems an odd choice. The same may be true for your audience. A traditional choice for programming events may be pizza and you probably can hardly go wrong with this all-time favorite. However, there may be better lunch options that can be distributed much easier, such as onigiri for example. 

Drinks can be organized in the same fashion depending on your audience’s preferences. Decide if you want to offer alcoholic options for example or if you need both, hot and cold drinks at the same time.


## Room setup

Last but not least, decide on the right room. A coding cafe can be organized online which comes with its own challenges. If you decide to organize an in-person event, you need to book a room that fits the needs of your event. 

Things you may need to consider are:

- Room size;
- Convenient location of the room;
- Accessibility of the room;
- Findability of the room;
- Number of power outlets;
- Number of tables;
- Are food and drink consumption allowed?;
- Presenter options.
 

All in all, make sure that the idea of your programming cafe fits into the chosen room. 30 participants may not fit in a common meeting room. A room at a non-central building may be a barrier for your community since they need to travel there. Also make sure that your participants will be able to access the room, even if they don’t have access cards for example. Investing time into printing way points may pay off since it minimizes the risk that your participants get lost on the way to you. As an alternative, you can also provide a detailed description of how to get there in your invitation. Make sure that the room is fit for programming needs, e.g. power outlets and tables are required. As an alternative, you can organize extension cables or similar. Think also about your format: do you need a screen for presenting or a flipchart or room to freely move around. If you order pizza, make sure you are not thrown out of the room for smuggling greasy food into an auditorium.

