name: Check links

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # Run at 00:00 UTC every Sunday
    - cron: "0 0 1 * *"

jobs:
  links:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.qmd' --max-retries 2 --accept '200..=204, 429'
          fail: true
